batch_size: 128
beta1: 0.99
beta2: 0.999
cnn_feature: 64
cnn_filter: 128
delta_loss: 0.001
dropout: 0.3
enableFrame: false
epochs: 35
fft_size: 512
gamma: 0.3
hop_size: 256
load_weight: false
lr: 0.001
model_name: cnnA20240515_004029
model_type: cnnA
optimizer_type: 1
patience: 5
random_seed: 34
save: true
save_model_epoch: 5
scheduler_type: 1
score_step: 0.2
shuffle: true
smooth: true
spilt_rate:
- 0.8
- 0.1
- 0.1
step_size: 10
weight_decay: 0
