batch_size: 4
beta1: 0.99
beta2: 0.999
cnn_feature: 64
cnn_filter: 128
delta_loss: 0.0002
dropout: 0.3
enable_frame: true
epochs: 15
expire: false
fft_size: 512
focal_gamma: 2
gamma: 0.3
hop_size: 256
iter_step: 100
iteration: 18000
load_weight: false
lr: 5.0e-05
mask_target: null
model2_type: cnnA
model_name: dpcrn_grlcnnA20240615_145932
model_type: dpcrn_grl
normalize_output: true
now_time: '20240615_145932'
optimizer_type: 3
patience: 5
qn_input_type: 1
random_seed: 34
save: true
save_model_epoch: 5
save_model_step: 10
scheduler_type: 1
score_class_num: 20
score_step: 0.2
se_input_type: 2
shuffle: true
smooth: true
spilt_rate:
- 0.8
- 0.1
- 0.1
step_size: 10
weight_decay: 0
