batch_size: 12
beta1: 0.99
beta2: 0.999
cnn_feature: 64
cnn_filter: 128
delta_loss: 0.001
dropout: 0.3
enable_frame: true
epochs: 35
fft_size: 512
focal_gamma: 2
gamma: 0.3
hop_size: 256
load_weight: false
lr: 0.0005
model2_type: null
model_name: hasa20240522_173240
model_type: hasa
normalize_output: true
now_time: '20240522_173240'
optimizer_type: 3
patience: 5
random_seed: 34
save: true
save_model_epoch: 5
scheduler_type: 1
score_class_num: 20
score_step: 0.2
se_input_type: 2
shuffle: true
smooth: true
spilt_rate:
- 0.8
- 0.1
- 0.1
step_size: 10
weight_decay: 0
