batch_size: 128
beta1: 0.99
beta2: 0.999
delta_loss: 0.001
dropout: 0.3
enableFrame: true
epochs: 40
fft_size: 512
gamma: 0.3
hop_size: 256
load_weight: false
lr: 0.001
model_name: lstmA20240511_090117
model_type: lstmA
optimizer_type: 3
patience: 5
random_seed: 34
save: true
save_model_epoch: 5
scheduler_type: 1
score_step: 0.5
shuffle: true
spilt_rate:
- 0.8
- 0.1
- 0.1
step_size: 10
weight_decay: 0
